#!/bin/bash
set -e

case "$1" in
    remove|purge)
        if [ -d "/var/lib/polaric/mapcache" ]; then
            rm -R /var/lib/polaric/mapcache
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
