#!/bin/bash
set -e


case "$1" in
    configure|reconfigure)
        
        if [[ ! -d "/usr/share/polaric" ]]; then
            mkdir /usr/share/polaric
        fi
        if [[ -L "/usr/share/polaric/icons" ]]; then
            rm /usr/share/polaric/icons
        fi
        ln -s /var/lib/polaric/webapp2/aprsd/icons/ /usr/share/polaric/
        
        a2enmod expires > /dev/null 2>&1
        a2enmod deflate > /dev/null 2>&1
        a2enmod ssl > /dev/null 2>&1
        a2enmod proxy > /dev/null 2>&1
        a2enmod proxy_http > /dev/null 2>&1
        a2enmod proxy_wstunnel > /dev/null 2>&1
        
        if [[ -f "/etc/apache2/sites-enabled/aprs.conf" ]]; then
            a2dissite aprs.conf > /dev/null 2>&1
        fi
        
        if [[ ! -f "/etc/apache2/sites-enabled/aprs_ssl.conf" ]]; then
            a2ensite aprs_ssl.conf > /dev/null 2>&1 
        fi
        if [ ! "$DOCKER_BUILD" = true ]; then
            apache2ctl restart
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
