#!/bin/bash
set -e


case "$1" in
    configure|reconfigure)
        a2enmod expires > /dev/null 2>&1
        a2enmod deflate > /dev/null 2>&1
        if [[ ! -f "/etc/apache2/sites-enabled/aprs.conf" ]]; then
            a2ensite aprs.conf > /dev/null 2>&1 
        fi
        chown www-data:polaric /var/lib/polaric/mapcache
        chmod 775 /var/lib/polaric/mapcache
        chown www-data:polaric /var/lib/polaric/mapcache/*.db
        chmod 664 /var/lib/polaric/mapcache/*.db
        
        apache2ctl restart
        
        if [[ ! -d "/usr/share/polaric" ]]; then
            mkdir /usr/share/polaric
        fi
        if [[ -L "/usr/share/polaric/icons" ]]; then
            rm /usr/share/polaric/icons
        fi
        ln -s /var/lib/polaric/webapp2/aprsd/icons/ /usr/share/polaric/
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
