#!/bin/bash
set -e


case "$1" in
    install|upgrade)
        if [[ ! -d "/var/lib/polaric" ]]; then
            mkdir /var/lib/polaric
        fi
        if [[ ! -d "/var/lib/polaric/mapcache" ]]; then
            mkdir /var/lib/polaric/mapcache
        fi
          
        if ! id polaric > /dev/null 2>&1 ; then
            adduser --quiet --system --home /var/lib/polaric --no-create-home \
                --group --disabled-password --shell /bin/false \
                polaric
            usermod -G dialout polaric
        fi
        chown www-data:polaric /var/lib/polaric/mapcache
        chmod 2775 /var/lib/polaric/mapcache
        if ls /var/lib/polaric/mapcache/*.db > /dev/null 2>%1; then
            chown www-data:polaric /var/lib/polaric/mapcache/*.db
            chmod 664 /var/lib/polaric/mapcache/*.db
        fi
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
