/**
 * Copyright (c) 2019, Njaal Dolonen, Nicolay Skjelbred, Jan-Magnus Solheim. 
 * All rights reserved. See LICENSE for more detail.  
 * */ 

/**
 * Icons downloaded from: https://mapicons.mapsmarker.com
 * Icons licenced under Creative Commons 3.0
 * for more information check _readme-license.txt in /images/iconpack/
 * */

//Autogenerated Mithril Mount for icons.
//This code was generated with iconPackToMithril.py
const iconTools =
{
     view: function()
     {
          return m("div",
          {"id":"icontools"},
          [
               m("div",
               {"id":"iconContainer"}, 
               [
                    //Icon Number:1 Name:aed-2.png
                    m("img",
                    {
                         "src":"images/iconpack/aed-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-aed-2",
                         "title":"aed-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:2 Name:aircraftsmall.png
                    m("img",
                    {
                         "src":"images/iconpack/aircraftsmall.png",
                         "class":"drawIcons",
                         "id":"markerIcon-aircraftsmall",
                         "title":"aircraftsmall",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:3 Name:airport.png
                    m("img",
                    {
                         "src":"images/iconpack/airport.png",
                         "class":"drawIcons",
                         "id":"markerIcon-airport",
                         "title":"airport",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:4 Name:avalanche1.png
                    m("img",
                    {
                         "src":"images/iconpack/avalanche1.png",
                         "class":"drawIcons",
                         "id":"markerIcon-avalanche1",
                         "title":"avalanche1",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:5 Name:blast.png
                    m("img",
                    {
                         "src":"images/iconpack/blast.png",
                         "class":"drawIcons",
                         "id":"markerIcon-blast",
                         "title":"blast",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:6 Name:boat.png
                    m("img",
                    {
                         "src":"images/iconpack/boat.png",
                         "class":"drawIcons",
                         "id":"markerIcon-boat",
                         "title":"boat",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:7 Name:bomb.png
                    m("img",
                    {
                         "src":"images/iconpack/bomb.png",
                         "class":"drawIcons",
                         "id":"markerIcon-bomb",
                         "title":"bomb",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:8 Name:bunker-2-2.png
                    m("img",
                    {
                         "src":"images/iconpack/bunker-2-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-bunker-2-2",
                         "title":"bunker-2-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:9 Name:bus.png
                    m("img",
                    {
                         "src":"images/iconpack/bus.png",
                         "class":"drawIcons",
                         "id":"markerIcon-bus",
                         "title":"bus",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:10 Name:busstop.png
                    m("img",
                    {
                         "src":"images/iconpack/busstop.png",
                         "class":"drawIcons",
                         "id":"markerIcon-busstop",
                         "title":"busstop",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:11 Name:campfire-2.png
                    m("img",
                    {
                         "src":"images/iconpack/campfire-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-campfire-2",
                         "title":"campfire-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:12 Name:car.png
                    m("img",
                    {
                         "src":"images/iconpack/car.png",
                         "class":"drawIcons",
                         "id":"markerIcon-car",
                         "title":"car",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:13 Name:caraccident.png
                    m("img",
                    {
                         "src":"images/iconpack/caraccident.png",
                         "class":"drawIcons",
                         "id":"markerIcon-caraccident",
                         "title":"caraccident",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:14 Name:caution.png
                    m("img",
                    {
                         "src":"images/iconpack/caution.png",
                         "class":"drawIcons",
                         "id":"markerIcon-caution",
                         "title":"caution",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:15 Name:coffee.png
                    m("img",
                    {
                         "src":"images/iconpack/coffee.png",
                         "class":"drawIcons",
                         "id":"markerIcon-coffee",
                         "title":"coffee",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:16 Name:comment-map-icon.png
                    m("img",
                    {
                         "src":"images/iconpack/comment-map-icon.png",
                         "class":"drawIcons",
                         "id":"markerIcon-comment-map-icon",
                         "title":"comment-map-icon",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:17 Name:conversation-map-icon.png
                    m("img",
                    {
                         "src":"images/iconpack/conversation-map-icon.png",
                         "class":"drawIcons",
                         "id":"markerIcon-conversation-map-icon",
                         "title":"conversation-map-icon",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:18 Name:crimescene.png
                    m("img",
                    {
                         "src":"images/iconpack/crimescene.png",
                         "class":"drawIcons",
                         "id":"markerIcon-crimescene",
                         "title":"crimescene",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:19 Name:disability.png
                    m("img",
                    {
                         "src":"images/iconpack/disability.png",
                         "class":"drawIcons",
                         "id":"markerIcon-disability",
                         "title":"disability",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:20 Name:doublebendright.png
                    m("img",
                    {
                         "src":"images/iconpack/doublebendright.png",
                         "class":"drawIcons",
                         "id":"markerIcon-doublebendright",
                         "title":"doublebendright",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:21 Name:earthquake-3.png
                    m("img",
                    {
                         "src":"images/iconpack/earthquake-3.png",
                         "class":"drawIcons",
                         "id":"markerIcon-earthquake-3",
                         "title":"earthquake-3",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:22 Name:fallingrocks.png
                    m("img",
                    {
                         "src":"images/iconpack/fallingrocks.png",
                         "class":"drawIcons",
                         "id":"markerIcon-fallingrocks",
                         "title":"fallingrocks",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:23 Name:ferry.png
                    m("img",
                    {
                         "src":"images/iconpack/ferry.png",
                         "class":"drawIcons",
                         "id":"markerIcon-ferry",
                         "title":"ferry",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:24 Name:fillingstation.png
                    m("img",
                    {
                         "src":"images/iconpack/fillingstation.png",
                         "class":"drawIcons",
                         "id":"markerIcon-fillingstation",
                         "title":"fillingstation",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:25 Name:fire-hydrant-2.png
                    m("img",
                    {
                         "src":"images/iconpack/fire-hydrant-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-fire-hydrant-2",
                         "title":"fire-hydrant-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:26 Name:fire.png
                    m("img",
                    {
                         "src":"images/iconpack/fire.png",
                         "class":"drawIcons",
                         "id":"markerIcon-fire",
                         "title":"fire",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:27 Name:fireexstinguisher.png
                    m("img",
                    {
                         "src":"images/iconpack/fireexstinguisher.png",
                         "class":"drawIcons",
                         "id":"markerIcon-fireexstinguisher",
                         "title":"fireexstinguisher",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:28 Name:firemen.png
                    m("img",
                    {
                         "src":"images/iconpack/firemen.png",
                         "class":"drawIcons",
                         "id":"markerIcon-firemen",
                         "title":"firemen",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:29 Name:firstaid.png
                    m("img",
                    {
                         "src":"images/iconpack/firstaid.png",
                         "class":"drawIcons",
                         "id":"markerIcon-firstaid",
                         "title":"firstaid",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:30 Name:flood.png
                    m("img",
                    {
                         "src":"images/iconpack/flood.png",
                         "class":"drawIcons",
                         "id":"markerIcon-flood",
                         "title":"flood",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:31 Name:footprint.png
                    m("img",
                    {
                         "src":"images/iconpack/footprint.png",
                         "class":"drawIcons",
                         "id":"markerIcon-footprint",
                         "title":"footprint",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:32 Name:fourbyfour.png
                    m("img",
                    {
                         "src":"images/iconpack/fourbyfour.png",
                         "class":"drawIcons",
                         "id":"markerIcon-fourbyfour",
                         "title":"fourbyfour",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:33 Name:harbor.png
                    m("img",
                    {
                         "src":"images/iconpack/harbor.png",
                         "class":"drawIcons",
                         "id":"markerIcon-harbor",
                         "title":"harbor",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:34 Name:helicopter.png
                    m("img",
                    {
                         "src":"images/iconpack/helicopter.png",
                         "class":"drawIcons",
                         "id":"markerIcon-helicopter",
                         "title":"helicopter",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:35 Name:highway.png
                    m("img",
                    {
                         "src":"images/iconpack/highway.png",
                         "class":"drawIcons",
                         "id":"markerIcon-highway",
                         "title":"highway",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:36 Name:hiking.png
                    m("img",
                    {
                         "src":"images/iconpack/hiking.png",
                         "class":"drawIcons",
                         "id":"markerIcon-hiking",
                         "title":"hiking",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:37 Name:home-2.png
                    m("img",
                    {
                         "src":"images/iconpack/home-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-home-2",
                         "title":"home-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:38 Name:hospital-building.png
                    m("img",
                    {
                         "src":"images/iconpack/hospital-building.png",
                         "class":"drawIcons",
                         "id":"markerIcon-hospital-building",
                         "title":"hospital-building",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:39 Name:house.png
                    m("img",
                    {
                         "src":"images/iconpack/house.png",
                         "class":"drawIcons",
                         "id":"markerIcon-house",
                         "title":"house",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:40 Name:hunting.png
                    m("img",
                    {
                         "src":"images/iconpack/hunting.png",
                         "class":"drawIcons",
                         "id":"markerIcon-hunting",
                         "title":"hunting",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:41 Name:icy_road.png
                    m("img",
                    {
                         "src":"images/iconpack/icy_road.png",
                         "class":"drawIcons",
                         "id":"markerIcon-icy_road",
                         "title":"icy_road",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:42 Name:information.png
                    m("img",
                    {
                         "src":"images/iconpack/information.png",
                         "class":"drawIcons",
                         "id":"markerIcon-information",
                         "title":"information",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:43 Name:jeep.png
                    m("img",
                    {
                         "src":"images/iconpack/jeep.png",
                         "class":"drawIcons",
                         "id":"markerIcon-jeep",
                         "title":"jeep",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:44 Name:lake.png
                    m("img",
                    {
                         "src":"images/iconpack/lake.png",
                         "class":"drawIcons",
                         "id":"markerIcon-lake",
                         "title":"lake",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:45 Name:lighthouse-2.png
                    m("img",
                    {
                         "src":"images/iconpack/lighthouse-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-lighthouse-2",
                         "title":"lighthouse-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:46 Name:linedown.png
                    m("img",
                    {
                         "src":"images/iconpack/linedown.png",
                         "class":"drawIcons",
                         "id":"markerIcon-linedown",
                         "title":"linedown",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:47 Name:lodging_0star.png
                    m("img",
                    {
                         "src":"images/iconpack/lodging_0star.png",
                         "class":"drawIcons",
                         "id":"markerIcon-lodging_0star",
                         "title":"lodging_0star",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:48 Name:mainroad.png
                    m("img",
                    {
                         "src":"images/iconpack/mainroad.png",
                         "class":"drawIcons",
                         "id":"markerIcon-mainroad",
                         "title":"mainroad",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:49 Name:male-2.png
                    m("img",
                    {
                         "src":"images/iconpack/male-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-male-2",
                         "title":"male-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:50 Name:military.png
                    m("img",
                    {
                         "src":"images/iconpack/military.png",
                         "class":"drawIcons",
                         "id":"markerIcon-military",
                         "title":"military",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:51 Name:mine.png
                    m("img",
                    {
                         "src":"images/iconpack/mine.png",
                         "class":"drawIcons",
                         "id":"markerIcon-mine",
                         "title":"mine",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:52 Name:motorcycle.png
                    m("img",
                    {
                         "src":"images/iconpack/motorcycle.png",
                         "class":"drawIcons",
                         "id":"markerIcon-motorcycle",
                         "title":"motorcycle",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:53 Name:mountains.png
                    m("img",
                    {
                         "src":"images/iconpack/mountains.png",
                         "class":"drawIcons",
                         "id":"markerIcon-mountains",
                         "title":"mountains",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:54 Name:oilrig2.png
                    m("img",
                    {
                         "src":"images/iconpack/oilrig2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-oilrig2",
                         "title":"oilrig2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:55 Name:parkinggarage.png
                    m("img",
                    {
                         "src":"images/iconpack/parkinggarage.png",
                         "class":"drawIcons",
                         "id":"markerIcon-parkinggarage",
                         "title":"parkinggarage",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:56 Name:pin-export.png
                    m("img",
                    {
                         "src":"images/iconpack/pin-export.png",
                         "class":"drawIcons",
                         "id":"markerIcon-pin-export",
                         "title":"pin-export",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:57 Name:planecrash.png
                    m("img",
                    {
                         "src":"images/iconpack/planecrash.png",
                         "class":"drawIcons",
                         "id":"markerIcon-planecrash",
                         "title":"planecrash",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:58 Name:police.png
                    m("img",
                    {
                         "src":"images/iconpack/police.png",
                         "class":"drawIcons",
                         "id":"markerIcon-police",
                         "title":"police",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:59 Name:prison.png
                    m("img",
                    {
                         "src":"images/iconpack/prison.png",
                         "class":"drawIcons",
                         "id":"markerIcon-prison",
                         "title":"prison",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:60 Name:radiation.png
                    m("img",
                    {
                         "src":"images/iconpack/radiation.png",
                         "class":"drawIcons",
                         "id":"markerIcon-radiation",
                         "title":"radiation",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:61 Name:radio-station-2.png
                    m("img",
                    {
                         "src":"images/iconpack/radio-station-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-radio-station-2",
                         "title":"radio-station-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:62 Name:repair.png
                    m("img",
                    {
                         "src":"images/iconpack/repair.png",
                         "class":"drawIcons",
                         "id":"markerIcon-repair",
                         "title":"repair",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:63 Name:rescue-2.png
                    m("img",
                    {
                         "src":"images/iconpack/rescue-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-rescue-2",
                         "title":"rescue-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:64 Name:river-2.png
                    m("img",
                    {
                         "src":"images/iconpack/river-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-river-2",
                         "title":"river-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:65 Name:rowboat.png
                    m("img",
                    {
                         "src":"images/iconpack/rowboat.png",
                         "class":"drawIcons",
                         "id":"markerIcon-rowboat",
                         "title":"rowboat",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:66 Name:school.png
                    m("img",
                    {
                         "src":"images/iconpack/school.png",
                         "class":"drawIcons",
                         "id":"markerIcon-school",
                         "title":"school",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:67 Name:septic_tank.png
                    m("img",
                    {
                         "src":"images/iconpack/septic_tank.png",
                         "class":"drawIcons",
                         "id":"markerIcon-septic_tank",
                         "title":"septic_tank",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:68 Name:shipwreck.png
                    m("img",
                    {
                         "src":"images/iconpack/shipwreck.png",
                         "class":"drawIcons",
                         "id":"markerIcon-shipwreck",
                         "title":"shipwreck",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:69 Name:shooting.png
                    m("img",
                    {
                         "src":"images/iconpack/shooting.png",
                         "class":"drawIcons",
                         "id":"markerIcon-shooting",
                         "title":"shooting",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:70 Name:shootingrange.png
                    m("img",
                    {
                         "src":"images/iconpack/shootingrange.png",
                         "class":"drawIcons",
                         "id":"markerIcon-shootingrange",
                         "title":"shootingrange",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:71 Name:snowmobiling.png
                    m("img",
                    {
                         "src":"images/iconpack/snowmobiling.png",
                         "class":"drawIcons",
                         "id":"markerIcon-snowmobiling",
                         "title":"snowmobiling",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:72 Name:stop.png
                    m("img",
                    {
                         "src":"images/iconpack/stop.png",
                         "class":"drawIcons",
                         "id":"markerIcon-stop",
                         "title":"stop",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:73 Name:tires.png
                    m("img",
                    {
                         "src":"images/iconpack/tires.png",
                         "class":"drawIcons",
                         "id":"markerIcon-tires",
                         "title":"tires",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:74 Name:toilets.png
                    m("img",
                    {
                         "src":"images/iconpack/toilets.png",
                         "class":"drawIcons",
                         "id":"markerIcon-toilets",
                         "title":"toilets",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:75 Name:tollstation.png
                    m("img",
                    {
                         "src":"images/iconpack/tollstation.png",
                         "class":"drawIcons",
                         "id":"markerIcon-tollstation",
                         "title":"tollstation",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:76 Name:tools.png
                    m("img",
                    {
                         "src":"images/iconpack/tools.png",
                         "class":"drawIcons",
                         "id":"markerIcon-tools",
                         "title":"tools",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:77 Name:townhouse.png
                    m("img",
                    {
                         "src":"images/iconpack/townhouse.png",
                         "class":"drawIcons",
                         "id":"markerIcon-townhouse",
                         "title":"townhouse",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:78 Name:toxic.png
                    m("img",
                    {
                         "src":"images/iconpack/toxic.png",
                         "class":"drawIcons",
                         "id":"markerIcon-toxic",
                         "title":"toxic",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:79 Name:train.png
                    m("img",
                    {
                         "src":"images/iconpack/train.png",
                         "class":"drawIcons",
                         "id":"markerIcon-train",
                         "title":"train",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:80 Name:tramway.png
                    m("img",
                    {
                         "src":"images/iconpack/tramway.png",
                         "class":"drawIcons",
                         "id":"markerIcon-tramway",
                         "title":"tramway",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:81 Name:trash.png
                    m("img",
                    {
                         "src":"images/iconpack/trash.png",
                         "class":"drawIcons",
                         "id":"markerIcon-trash",
                         "title":"trash",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:82 Name:trolley.png
                    m("img",
                    {
                         "src":"images/iconpack/trolley.png",
                         "class":"drawIcons",
                         "id":"markerIcon-trolley",
                         "title":"trolley",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:83 Name:truck3.png
                    m("img",
                    {
                         "src":"images/iconpack/truck3.png",
                         "class":"drawIcons",
                         "id":"markerIcon-truck3",
                         "title":"truck3",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:84 Name:tunnel.png
                    m("img",
                    {
                         "src":"images/iconpack/tunnel.png",
                         "class":"drawIcons",
                         "id":"markerIcon-tunnel",
                         "title":"tunnel",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:85 Name:underground.png
                    m("img",
                    {
                         "src":"images/iconpack/underground.png",
                         "class":"drawIcons",
                         "id":"markerIcon-underground",
                         "title":"underground",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:86 Name:walkingtour.png
                    m("img",
                    {
                         "src":"images/iconpack/walkingtour.png",
                         "class":"drawIcons",
                         "id":"markerIcon-walkingtour",
                         "title":"walkingtour",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:87 Name:watercraft.png
                    m("img",
                    {
                         "src":"images/iconpack/watercraft.png",
                         "class":"drawIcons",
                         "id":"markerIcon-watercraft",
                         "title":"watercraft",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:88 Name:waterfall-2.png
                    m("img",
                    {
                         "src":"images/iconpack/waterfall-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-waterfall-2",
                         "title":"waterfall-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:89 Name:wetlands.png
                    m("img",
                    {
                         "src":"images/iconpack/wetlands.png",
                         "class":"drawIcons",
                         "id":"markerIcon-wetlands",
                         "title":"wetlands",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:90 Name:wind-2.png
                    m("img",
                    {
                         "src":"images/iconpack/wind-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-wind-2",
                         "title":"wind-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:91 Name:windturbine.png
                    m("img",
                    {
                         "src":"images/iconpack/windturbine.png",
                         "class":"drawIcons",
                         "id":"markerIcon-windturbine",
                         "title":"windturbine",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:92 Name:workshop.png
                    m("img",
                    {
                         "src":"images/iconpack/workshop.png",
                         "class":"drawIcons",
                         "id":"markerIcon-workshop",
                         "title":"workshop",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:93 Name:world.png
                    m("img",
                    {
                         "src":"images/iconpack/world.png",
                         "class":"drawIcons",
                         "id":"markerIcon-world",
                         "title":"world",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:94 Name:you-are-here-2.png
                    m("img",
                    {
                         "src":"images/iconpack/you-are-here-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-you-are-here-2",
                         "title":"you-are-here-2",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:95 Name:zoo.png
                    m("img",
                    {
                         "src":"images/iconpack/zoo.png",
                         "class":"drawIcons",
                         "id":"markerIcon-zoo",
                         "title":"zoo",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
                    //Icon Number:96 Name:zoom.png
                    m("img",
                    {
                         "src":"images/iconpack/zoom.png",
                         "class":"drawIcons",
                         "id":"markerIcon-zoom",
                         "title":"zoom",
                         onclick: (e) =>
                         {markerIcons_click(e)}
                    }),
               ])
          ])
     }
}