/**
 * Copyright (c) 2019, Njaal Dolonen, Nicolay Skjelbred, Jan-Magnus Solheim.
 * All rights reserved. See LICENSE for more detail.
 * */

var snow = window.snow;

/**
 * Icons downloaded from: https://mapicons.mapsmarker.com
 * Icons licenced under Creative Commons 3.0
 * for more information check _readme-license.txt in /images/iconpack/
 * */

//Autogenerated Mithril Mount for icons.
//This code was generated with iconPackToMithril.py
snow.iconTools =
{
     view: function()
     {
          return m("div",
          {"id":"icontools"},
          [
               m("div",
               {"id":"iconContainer"}, 
               [
                    //Icon Number:1 Name:1.Bunker.png
                    m("img",
                    {
                         "src":"images/iconpack/1.Bunker.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Bunker",
                         "title":"Bunker",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:2 Name:1.Factory.png
                    m("img",
                    {
                         "src":"images/iconpack/1.Factory.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Factory",
                         "title":"Factory",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:3 Name:1.Oil-rig2.png
                    m("img",
                    {
                         "src":"images/iconpack/1.Oil-rig2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Oil-rig2",
                         "title":"Oil-rig2",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:4 Name:1.Radio-station.png
                    m("img",
                    {
                         "src":"images/iconpack/1.Radio-station.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Radio-station",
                         "title":"Radio-station",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:5 Name:1.Warehouse-2.png
                    m("img",
                    {
                         "src":"images/iconpack/1.Warehouse-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Warehouse-2",
                         "title":"Warehouse-2",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:6 Name:1.Wind-turbine.png
                    m("img",
                    {
                         "src":"images/iconpack/1.Wind-turbine.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Wind-turbine",
                         "title":"Wind-turbine",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:7 Name:2.Ambulance-boat.png
                    m("img",
                    {
                         "src":"images/iconpack/2.Ambulance-boat.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Ambulance-boat",
                         "title":"Ambulance-boat",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:8 Name:2.First-taid.png
                    m("img",
                    {
                         "src":"images/iconpack/2.First-taid.png",
                         "class":"drawIcons",
                         "id":"markerIcon-First-taid",
                         "title":"First-taid",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:9 Name:2.Footprint.png
                    m("img",
                    {
                         "src":"images/iconpack/2.Footprint.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Footprint",
                         "title":"Footprint",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:10 Name:2.Hospital-building.png
                    m("img",
                    {
                         "src":"images/iconpack/2.Hospital-building.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Hospital-building",
                         "title":"Hospital-building",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:11 Name:2.Medicine.png
                    m("img",
                    {
                         "src":"images/iconpack/2.Medicine.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Medicine",
                         "title":"Medicine",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:12 Name:2.Nursing-home.png
                    m("img",
                    {
                         "src":"images/iconpack/2.Nursing-home.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Nursing-home",
                         "title":"Nursing-home",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:13 Name:2.School-or-university.png
                    m("img",
                    {
                         "src":"images/iconpack/2.School-or-university.png",
                         "class":"drawIcons",
                         "id":"markerIcon-School-or-university",
                         "title":"School-or-university",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:14 Name:2.Summer-camp.png
                    m("img",
                    {
                         "src":"images/iconpack/2.Summer-camp.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Summer-camp",
                         "title":"Summer-camp",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:15 Name:2.Toilets.png
                    m("img",
                    {
                         "src":"images/iconpack/2.Toilets.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Toilets",
                         "title":"Toilets",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:16 Name:3.Aircraft-small.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Aircraft-small.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Aircraft-small",
                         "title":"Aircraft-small",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:17 Name:3.Airport.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Airport.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Airport",
                         "title":"Airport",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:18 Name:3.Ambulance.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Ambulance.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Ambulance",
                         "title":"Ambulance",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:19 Name:3.Barrier.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Barrier.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Barrier",
                         "title":"Barrier",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:20 Name:3.Bus.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Bus.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Bus",
                         "title":"Bus",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:21 Name:3.Car-fourbyfour.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Car-fourbyfour.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Car-fourbyfour",
                         "title":"Car-fourbyfour",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:22 Name:3.Car.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Car.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Car",
                         "title":"Car",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:23 Name:3.Caution.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Caution.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Caution",
                         "title":"Caution",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:24 Name:3.Disability.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Disability.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Disability",
                         "title":"Disability",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:25 Name:3.Ferry.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Ferry.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Ferry",
                         "title":"Ferry",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:26 Name:3.Fuel-fillingstation.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Fuel-fillingstation.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Fuel-fillingstation",
                         "title":"Fuel-fillingstation",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:27 Name:3.Harbor.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Harbor.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Harbor",
                         "title":"Harbor",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:28 Name:3.Helicopter.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Helicopter.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Helicopter",
                         "title":"Helicopter",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:29 Name:3.Parking.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Parking.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Parking",
                         "title":"Parking",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:30 Name:3.Railway.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Railway.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Railway",
                         "title":"Railway",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:31 Name:3.Repair.png
                    m("img",
                    {
                         "src":"images/iconpack/3.Repair.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Repair",
                         "title":"Repair",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:32 Name:4.Avalanche.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Avalanche.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Avalanche",
                         "title":"Avalanche",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:33 Name:4.Danger.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Danger.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Danger",
                         "title":"Danger",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:34 Name:4.Earthquake-3.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Earthquake-3.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Earthquake-3",
                         "title":"Earthquake-3",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:35 Name:4.Explosion-or-explosive.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Explosion-or-explosive.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Explosion-or-explosive",
                         "title":"Explosion-or-explosive",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:36 Name:4.Fire.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Fire.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Fire",
                         "title":"Fire",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:37 Name:4.Flood.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Flood.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Flood",
                         "title":"Flood",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:38 Name:4.Person-down.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Person-down.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Person-down",
                         "title":"Person-down",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:39 Name:4.Plane-accident.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Plane-accident.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Plane-accident",
                         "title":"Plane-accident",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:40 Name:4.Radiation.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Radiation.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Radiation",
                         "title":"Radiation",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:41 Name:4.Rescue.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Rescue.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Rescue",
                         "title":"Rescue",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:42 Name:4.Shooting.png
                    m("img",
                    {
                         "src":"images/iconpack/4.Shooting.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Shooting",
                         "title":"Shooting",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:43 Name:5.Coffee.png
                    m("img",
                    {
                         "src":"images/iconpack/5.Coffee.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Coffee",
                         "title":"Coffee",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:44 Name:5.Food.png
                    m("img",
                    {
                         "src":"images/iconpack/5.Food.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Food",
                         "title":"Food",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:45 Name:5.Lodging.png
                    m("img",
                    {
                         "src":"images/iconpack/5.Lodging.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Lodging",
                         "title":"Lodging",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:46 Name:5.Wi-Fi.png
                    m("img",
                    {
                         "src":"images/iconpack/5.Wi-Fi.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Wi-Fi",
                         "title":"Wi-Fi",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:47 Name:6.Number-1.png
                    m("img",
                    {
                         "src":"images/iconpack/6.Number-1.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Number-1",
                         "title":"Number-1",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:48 Name:6.Number-2.png
                    m("img",
                    {
                         "src":"images/iconpack/6.Number-2.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Number-2",
                         "title":"Number-2",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:49 Name:6.Number-3.png
                    m("img",
                    {
                         "src":"images/iconpack/6.Number-3.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Number-3",
                         "title":"Number-3",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
                    //Icon Number:50 Name:6.Number-4.png
                    m("img",
                    {
                         "src":"images/iconpack/6.Number-4.png",
                         "class":"drawIcons",
                         "id":"markerIcon-Number-4",
                         "title":"Number-4",
                         onclick: (e) =>
                         {snow.markerIcons_click(e)}
                    }),
               ])
          ])
     }
}