# Default setup for Polaric Webapp

<IfModule mod_ssl.c>

<VirtualHost *:443>



######################################
# Mapcache setup
######################################

<IfModule mapcache_module>
   MapCacheAlias /mapcache "/var/lib/polaric/webapp2/mapcache.xml"
</IfModule>


#############################################################
# SSL/TLS setup 
# Use self-signed snakeoil certificates by default. It is 
# recommended to use certificates signed by a CA if you have 
# more than a few users. For examle from lets encrypt. 
#############################################################

SSLEngine on
SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

#
# Setup of TLS protocols and ciphers supports a high level of security. 
# Support quantum-resistant session key establishment (if client supports it)
#
SSLProtocol -all +TLSv1.2 +TLSv1.3
SSLOpenSSLConfCmd Groups X25519MLKEM768:X25519:secp384r1:prime256v1
SSLHonorCipherOrder on
SSLCipherSuite HIGH:!aNULL:!eNULL:!MD5:!RC4:!3DES




###########################################################
# Set up the frontend server as a proxy for the backend
# Use prefix 'srv' for REST API and 'ws' for websockets
###########################################################

SSLProxyEngine On
ProxyPass /srv/ http://localhost:8081/ nocanon
ProxyPassReverse /srv/ http://localhost:8081/
SetEnv  proxy-nokeepalive 1
ProxyTimeout 180

# 
# FIX: Strips the Domain attribute from the pac4jCsrfToken cookie, 
# if domain=localhost
#
Header edit Set-Cookie "^(pac4jCsrfToken=.*?);\s*?[Dd]omain=localhost(;?.*)$" "$1$2"


<Location "/ws/">
   ProxyPass ws://localhost:8081/
   ProxyPassReverse ws://localhost:8081/
</Location>



####################################
# Default location of the webapp
####################################

Alias /aprs "/var/lib/polaric/webapp2"
<Directory /var/lib/polaric/webapp2>
  Options Indexes FollowSymLinks MultiViews
  AllowOverride None
  Require all granted
</Directory>


Alias /aprsd "/usr/share/polaric/"
<Directory /usr/share/polaric>
  Options Indexes FollowSymLinks MultiViews
  AllowOverride None
  Require all granted
</Directory>



##########################################
# Compression
##########################################

AddOutputFilterByType DEFLATE text/plain
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/xml
AddOutputFilterByType DEFLATE text/css

AddOutputFilterByType DEFLATE application/xml
AddOutputFilterByType DEFLATE application/xhtml+xml
AddOutputFilterByType DEFLATE application/rss+xml
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE application/x-javascript

</VirtualHost>
</IfModule>
